baseurl = "/"
languageCode = "es"
title = "Canister"

[params]
  description = "Bar de sabores."
  ga_analytics = 'G-VKKGWY8GL7'

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1

[[menu.main]]
    name = "Pedidos"
    url  = "/pedidos"
    weight = 5

[[menu.main]]
    name = "Galería"
    url  = "/gallery"
    weight = 2

[[menu.main]]
    name = "Los Platos"
    url  = "/food"
    weight = 3

[[menu.main]]
    name = "Las Bebidas"
    url  = "/drinks"
    weight = 4

