baseurl = "/"
languageCode = "es"
title = "Baster"

[params]
  description = "Bar de sabores."

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1

[[menu.main]]
    name = "Pedido"
    url  = "/pedido"
    weight = 2
